### ISSUE TITLE
mention user in chat, doesnt always seem to find freshly changed/joined user

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1049]
https://github.com/acterglobal/a3/assets/77483554/22f3ca93-ffec-402b-8025-f5c486805804

**Comment by emilvincentz** [comment]
@gnunicorn yes I also tried dan

**Comment by kumarpalsinh25** [comment]
@gnunicorn @emilvincentz 
Is this issue is still exists? If yes then may I know steps to reproduce it?

I have checked it with the same scenario and it is working fine. Attaching screen recoding for the reference.


https://github.com/acterglobal/a3/assets/51526480/60c055d0-f085-4767-ac8d-5018dd06cbcf

**Comment by gnunicorn** [comment]
I _think_ I have some idea what causes things like that. I have found two cases:

1. if they have a displayname differently or changed recently, and you use the user-id they don't seem to show up and/or
2. when they recently joined the chat, they don't appear to be in the list either. I also noticed that the member counter didn't update when they joined...
