### ISSUE TITLE
Rejecting invites doens't work.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1219]
Currently you need to click reject and then join to reject a chat. See video below 
![Uploading 290756301...]

**Comment by gnunicorn** [comment]
@emilvincentz screenshot missing...

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/33a19853-8c69-4048-8fc2-aaf80e21f8f1

**Comment by kumarpalsinh25** [comment]
@bitfriend 
I have checked details about this issue. 

There is an exception throwing from rust side when we do reject invitation for DM.

File Name: 
`features/activities/widgets/invitation_card.dart`

Issue Code:
`await invitation.reject()`

Error Message: 
`Can't get a room we are not invited` 

Side note:
- Reject invitation is working for Groups. Only issue is with DM Invites.

**Comment by gnunicorn** [comment]
@bitfriend could you please take a look? Looks like we are expecting to have `joined` a room that we didn't yet `join` for us to reject the invite...

**Comment by kumarpalsinh25** [comment]
@bitfriend @gnunicorn 
Sharing video for some additional information which might help to find the root cause.

https://github.com/acterglobal/a3/assets/51526480/e553acab-fe98-4601-b222-3d57ca650e83

Key thing: As shown on the above video , it looks like `DM reject invitation` gets proceed when we click on `Decline` button but nothing happen on Acter app. Acter app showing this error `Can't get a room we are not invited` on logs.
