### ISSUE TITLE
Rethink the "no parent space selected" labelling

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#870]
The UI for “no parent space selected” is not self-explaining for when creating space and other objects. Rethink that part of the design...

relates to: [Product Terminology - Change Proposal](https://github.com/acterglobal/a3/issues/867)

**Comment by emilvincentz** [comment]
A suggestion: 
"Connect to an existing space (optional)".

However to keep things more simple and less potentially confusing for people, i suggest that we actually hide this field when the user is creating a space from their Home Screen. 
Because: 
1. When users are creating a space from this location, I assume its oftentimes already the "highest" space.
2. They still have the option to link both to a parent and subspace in the "spaces page"
