### ISSUE TITLE
Logging in first time, the update page is shown by default, but home button is highlighted.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#941]
![Image](https://user-images.githubusercontent.com/77483554/267431440-0fa0b073-20d6-4752-addc-736f3141ea01.PNG)

**Comment by kumarpalsinh25** [comment]
@gnunicorn 

Not sure, but this looks like technical issue from [go_router](https://pub.dev/packages/go_router).
Debug the end-to-end flow related to this issue. Code looks fine but still we are not getting correct routing information.

**Comment by gnunicorn** [comment]
It appears that because we go through a `redirect`, the `routerInformation` provided by `go_router` to the provider isn't correctly updating the information ... not finding a bug report on the flutter repo right now, have to investigate whether we are doing something wrong, or if that is a go_router bug...
