### ISSUE TITLE
When updating the the content of pin and events, it doesnt always work.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#958]
See video below

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/ce328cf2-814a-4f51-9e2c-27c4c6c72650

**Comment by emilvincentz** [comment]
Not sure if this also related to this one, but i have some difficulties uploading pins. 
Concretely, it created the pin, but does not save the title.


https://github.com/acterglobal/a3/assets/77483554/567fd47d-0f50-4a04-a563-4695e17b569c

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is still persists? Can you check and confirm?

**Comment by emilvincentz** [comment]
yeah, still doesn't work

**Comment by emilvincentz** [comment]
It's like it's not being saved or at least the changes are not being displayed

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
I have just tested this flow on latest build. It seems to be working fine.

Reference:
https://github.com/acterglobal/a3/assets/51526480/8293cd88-80bf-4165-96a1-f5c99458c9dc

Few questions to find the root cause:
- Are you testing on latest build?
- Are you facing this issue on all of the your spaces? Can you can create new space and test this?
- Can you test this with different user account? so that we can come to know that if this is user specific

**Comment by emilvincentz** [comment]
hey @kumarpalsinh25 

- Pins works fine, but not with events. 
 I have tested again on the latest build.
but still doesnt work (see below video)

- It works fine with Pins and only seems to be on events now. 
howeverr still persist although created through new space.

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
It seems like your video is not attached with above comment. Can you upload the video again?

Note:
- Share flow of create event and update event both on the video to understand the issue.

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
I have test the same. It looks like Event creation is working but event update is not working.
@gtalha07 @bitfriend can you cross check once from the Rust side regarding this issue?
